2018-12-26 13:12:18.241 [error] <0.455.0> CRASH REPORT Process <0.455.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"host">> => <<"localhost:4000">>,<<"user-agent">> => <<"curl/7.61.0">>},host => <<"localhost">>,host_info => undefined,method => <<"GET">>,path => <<"/transactions">>,path_info => undefined,peer => {{127,0,0,1},53530},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 43
2018-12-26 13:12:18.261 [error] <0.249.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ElixirTryoutWeb.Endpoint.HTTP',<0.454.0>,1,<0.455.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"host">> => <<"localhost:4000">>,<<"user-agent">> => <<"curl/7.61.0">>},host => <<"localhost">>,host_info => undefined,method => <<"...">>,...}},...},...},...},...},...]},...}}
2018-12-26 13:27:12.289 [error] <0.475.0> Supervisor {<0.475.0>,ranch_acceptors_sup} had child {acceptor,<0.475.0>,100} started with ranch_acceptor:start_link(#Port<0.1031>, ranch_tcp, error_logger, <0.474.0>) at <0.575.0> exit with reason killed in context child_terminated
2018-12-26 13:27:12.289 [error] <0.475.0> Supervisor {<0.475.0>,ranch_acceptors_sup} had child {acceptor,<0.475.0>,99} started with ranch_acceptor:start_link(#Port<0.1031>, ranch_tcp, error_logger, <0.474.0>) at <0.574.0> exit with reason killed in context child_terminated
2018-12-26 13:27:12.290 [error] <0.475.0> Supervisor {<0.475.0>,ranch_acceptors_sup} had child {acceptor,<0.475.0>,99} started with ranch_acceptor:start_link(#Port<0.1031>, ranch_tcp, error_logger, <0.474.0>) at <0.574.0> exit with reason reached_max_restart_intensity in context shutdown
2018-12-26 13:27:12.290 [error] <0.475.0> Supervisor {<0.475.0>,ranch_acceptors_sup} had child {acceptor,<0.475.0>,98} started with ranch_acceptor:start_link(#Port<0.1031>, ranch_tcp, error_logger, <0.474.0>) at <0.573.0> exit with reason killed in context shutdown_error
2018-12-26 13:27:12.290 [error] <0.475.0> Supervisor {<0.475.0>,ranch_acceptors_sup} had child {acceptor,<0.475.0>,97} started with ranch_acceptor:start_link(#Port<0.1031>, ranch_tcp, error_logger, <0.474.0>) at <0.572.0> exit with reason killed in context shutdown_error
2018-12-26 13:27:12.290 [error] <0.475.0> Supervisor {<0.475.0>,ranch_acceptors_sup} had child {acceptor,<0.475.0>,96} started with ranch_acceptor:start_link(#Port<0.1031>, ranch_tcp, error_logger, <0.474.0>) at <0.571.0> exit with reason killed in context shutdown_error
2018-12-26 13:27:12.291 [error] <0.475.0> Supervisor {<0.475.0>,ranch_acceptors_sup} had child {acceptor,<0.475.0>,95} started with ranch_acceptor:start_link(#Port<0.1031>, ranch_tcp, error_logger, <0.474.0>) at <0.570.0> exit with reason killed in context shutdown_error
2018-12-26 13:27:12.291 [error] <0.475.0> Supervisor {<0.475.0>,ranch_acceptors_sup} had child {acceptor,<0.475.0>,94} started with ranch_acceptor:start_link(#Port<0.1031>, ranch_tcp, error_logger, <0.474.0>) at <0.569.0> exit with reason killed in context shutdown_error
2018-12-26 13:27:12.291 [error] <0.475.0> Supervisor {<0.475.0>,ranch_acceptors_sup} had child {acceptor,<0.475.0>,93} started with ranch_acceptor:start_link(#Port<0.1031>, ranch_tcp, error_logger, <0.474.0>) at <0.568.0> exit with reason killed in context shutdown_error
2018-12-26 13:27:12.291 [error] <0.475.0> Supervisor {<0.475.0>,ranch_acceptors_sup} had child {acceptor,<0.475.0>,92} started with ranch_acceptor:start_link(#Port<0.1031>, ranch_tcp, error_logger, <0.474.0>) at <0.567.0> exit with reason killed in context shutdown_error
2018-12-26 13:27:12.291 [error] <0.475.0> Supervisor {<0.475.0>,ranch_acceptors_sup} had child {acceptor,<0.475.0>,91} started with ranch_acceptor:start_link(#Port<0.1031>, ranch_tcp, error_logger, <0.474.0>) at <0.566.0> exit with reason killed in context shutdown_error
2018-12-26 13:27:12.292 [error] <0.475.0> Supervisor {<0.475.0>,ranch_acceptors_sup} had child {acceptor,<0.475.0>,90} started with ranch_acceptor:start_link(#Port<0.1031>, ranch_tcp, error_logger, <0.474.0>) at <0.565.0> exit with reason killed in context shutdown_error
2018-12-26 13:27:12.292 [error] <0.475.0> Supervisor {<0.475.0>,ranch_acceptors_sup} had child {acceptor,<0.475.0>,89} started with ranch_acceptor:start_link(#Port<0.1031>, ranch_tcp, error_logger, <0.474.0>) at <0.564.0> exit with reason killed in context shutdown_error
2018-12-26 13:27:12.292 [error] <0.475.0> Supervisor {<0.475.0>,ranch_acceptors_sup} had child {acceptor,<0.475.0>,88} started with ranch_acceptor:start_link(#Port<0.1031>, ranch_tcp, error_logger, <0.474.0>) at <0.563.0> exit with reason killed in context shutdown_error
2018-12-26 13:27:12.292 [error] <0.475.0> Supervisor {<0.475.0>,ranch_acceptors_sup} had child {acceptor,<0.475.0>,87} started with ranch_acceptor:start_link(#Port<0.1031>, ranch_tcp, error_logger, <0.474.0>) at <0.562.0> exit with reason killed in context shutdown_error
2018-12-26 13:27:12.292 [error] <0.475.0> Supervisor {<0.475.0>,ranch_acceptors_sup} had child {acceptor,<0.475.0>,86} started with ranch_acceptor:start_link(#Port<0.1031>, ranch_tcp, error_logger, <0.474.0>) at <0.561.0> exit with reason killed in context shutdown_error
2018-12-26 13:27:12.293 [error] <0.475.0> Supervisor {<0.475.0>,ranch_acceptors_sup} had child {acceptor,<0.475.0>,85} started with ranch_acceptor:start_link(#Port<0.1031>, ranch_tcp, error_logger, <0.474.0>) at <0.560.0> exit with reason killed in context shutdown_error
2018-12-26 13:27:12.293 [error] <0.475.0> Supervisor {<0.475.0>,ranch_acceptors_sup} had child {acceptor,<0.475.0>,84} started with ranch_acceptor:start_link(#Port<0.1031>, ranch_tcp, error_logger, <0.474.0>) at <0.559.0> exit with reason killed in context shutdown_error
2018-12-26 13:27:12.293 [error] <0.475.0> Supervisor {<0.475.0>,ranch_acceptors_sup} had child {acceptor,<0.475.0>,83} started with ranch_acceptor:start_link(#Port<0.1031>, ranch_tcp, error_logger, <0.474.0>) at <0.558.0> exit with reason killed in context shutdown_error
2018-12-26 13:27:12.293 [error] <0.475.0> Supervisor {<0.475.0>,ranch_acceptors_sup} had child {acceptor,<0.475.0>,82} started with ranch_acceptor:start_link(#Port<0.1031>, ranch_tcp, error_logger, <0.474.0>) at <0.557.0> exit with reason killed in context shutdown_error
2018-12-26 13:27:12.293 [error] <0.473.0> Supervisor {<0.473.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link('Elixir.ElixirTryoutWeb.Endpoint.HTTP', ranch_tcp) at <0.475.0> exit with reason shutdown in context child_terminated
2018-12-26 15:25:07.481 [error] <0.325.0> Supervisor 'Elixir.ElixirTryout.Supervisor' had child 'Elixir.DrainStop' started with 'Elixir.DrainStop':start_link([{timeout,10000},{endpoint,'Elixir.ElixirTryoutWeb.Endpoint'}]) at <0.463.0> exit with reason killed in context shutdown_error
2018-12-26 16:25:17.256 [error] <0.417.0>@rabbit_framing_amqp_0_9_1:shortstr_size:185 Supervisor {<0.417.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.77>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.419.0>, {<<"client 127.0.0.1:34247 -> 127.0.0.1:5672">>,1}) at <0.420.0> exit with reason bad argument in call to erlang:size(<0.389.0>) in rabbit_framing_amqp_0_9_1:shortstr_size/1 line 185 in context child_terminated
2018-12-26 16:25:17.257 [error] emulator Error in process <0.420.0> with exit value:
{badarg,[{erlang,size,[<0.389.0>],[]},{rabbit_framing_amqp_0_9_1,shortstr_size,1,[{file,"/home/mbohoslavskyi/elixir/elixir_tryout/deps/rabbit_common/src/rabbit_framing_amqp_0_9_1.erl"},{line,185}]},{rabbit_framing_amqp_0_9_1,encode_method_fields,1,[{file,"/home/mbohoslavskyi/elixir/elixir_tryout/deps/rabbit_common/src/rabbit_framing_amqp_0_9_1.erl"},{line,1098}]},{rabbit_binary_generator,build_simple_method_frame,3,[{file,"/home/mbohoslavskyi/elixir/elixir_tryout/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,59}]},{rabbit_writer,internal_send_command_async,2,[{file,"/home/mbohoslavskyi/elixir/elixir_tryout/deps/rabbit_common/src/rabbit_writer.erl"},{line,333}]},{rabbit_writer,handle_message,3,[{file,"/home/mbohoslavskyi/elixir/elixir_tryout/deps/rabbit_common/src/rabbit_writer.erl"},{line,209}]},{rabbit_writer,mainloop1,2,[{file,"/home/mbohoslavskyi/elixir/elixir_tryout/deps/rabbit_common/src/rabbit_writer.erl"},{line,193}]},{rabbit_writer,mainloop,2,[{file,"/home/mbohoslavskyi/elixir/elixir_tryout/deps/rabbit_common/src/rabbit_writer.erl"},{line,184}]}]}
2018-12-26 16:25:17.257 [error] <0.417.0> Supervisor {<0.417.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.77>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.419.0>, {<<"client 127.0.0.1:34247 -> 127.0.0.1:5672">>,1}) at <0.420.0> exit with reason reached_max_restart_intensity in context shutdown
2018-12-26 16:37:40.648 [error] <0.376.0> gen_server <0.376.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2018-12-26 16:37:40.655 [error] <0.376.0> CRASH REPORT Process <0.376.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1166
2018-12-26 16:37:40.655 [error] <0.375.0> Supervisor {<0.375.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:38023 -> 127.0.0.1:5672">>,1}) at <0.376.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2018-12-26 16:37:40.656 [error] <0.375.0> Supervisor {<0.375.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:38023 -> 127.0.0.1:5672">>,1}) at <0.376.0> exit with reason reached_max_restart_intensity in context shutdown
2018-12-26 16:40:33.767 [error] <0.430.0> gen_server <0.430.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2018-12-26 16:40:33.770 [error] <0.430.0> CRASH REPORT Process <0.430.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1166
2018-12-26 16:40:33.770 [error] <0.429.0> Supervisor {<0.429.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:35749 -> 127.0.0.1:5672">>,1}) at <0.430.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2018-12-26 16:40:33.770 [error] <0.429.0> Supervisor {<0.429.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:35749 -> 127.0.0.1:5672">>,1}) at <0.430.0> exit with reason reached_max_restart_intensity in context shutdown
2018-12-26 16:43:30.575 [error] <0.431.0> gen_server <0.431.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2018-12-26 16:43:30.578 [error] <0.431.0> CRASH REPORT Process <0.431.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1166
2018-12-26 16:43:30.578 [error] <0.430.0> Supervisor {<0.430.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:48679 -> 127.0.0.1:5672">>,1}) at <0.431.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2018-12-26 16:43:30.578 [error] <0.430.0> Supervisor {<0.430.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:48679 -> 127.0.0.1:5672">>,1}) at <0.431.0> exit with reason reached_max_restart_intensity in context shutdown
2018-12-26 16:44:19.062 [error] <0.432.0> gen_server <0.432.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2018-12-26 16:44:19.067 [error] <0.432.0> CRASH REPORT Process <0.432.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1166
2018-12-26 16:44:19.067 [error] <0.431.0> Supervisor {<0.431.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:55891 -> 127.0.0.1:5672">>,1}) at <0.432.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2018-12-26 16:44:19.068 [error] <0.431.0> Supervisor {<0.431.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:55891 -> 127.0.0.1:5672">>,1}) at <0.432.0> exit with reason reached_max_restart_intensity in context shutdown
2018-12-26 16:44:25.249 [error] <0.462.0> gen_server <0.462.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2018-12-26 16:44:25.249 [error] <0.462.0> CRASH REPORT Process <0.462.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1166
2018-12-26 16:44:25.250 [error] <0.461.0> Supervisor {<0.461.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:46033 -> 127.0.0.1:5672">>,1}) at <0.462.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2018-12-26 16:44:25.250 [error] <0.461.0> Supervisor {<0.461.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:46033 -> 127.0.0.1:5672">>,1}) at <0.462.0> exit with reason reached_max_restart_intensity in context shutdown
2018-12-26 16:48:50.192 [error] <0.419.0> gen_server <0.419.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2018-12-26 16:48:50.196 [error] <0.419.0> CRASH REPORT Process <0.419.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1166
2018-12-26 16:48:50.196 [error] <0.418.0> Supervisor {<0.418.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:34743 -> 127.0.0.1:5672">>,1}) at <0.419.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2018-12-26 16:48:50.196 [error] <0.418.0> Supervisor {<0.418.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:34743 -> 127.0.0.1:5672">>,1}) at <0.419.0> exit with reason reached_max_restart_intensity in context shutdown
